/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engsoft.view;

import com.mysql.jdbc.PreparedStatement;
import connection.ConnectionFactory;
import dao.Alunodao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Aluno;

/**
 *
 * @author vinicius
 */
public class Perfil extends javax.swing.JFrame {

    Aluno aux;
    Aluno aux2;
    Alunodao dao = new Alunodao();

    /**
     * Creates new form CadastroUsuario1
     */
    public Perfil(Aluno a) {
        initComponents();

        aux = a;

        Perfil.setVisible(true);
        AlterarSenha.setVisible(false);
        AlterarNomeLogin.setVisible(false);
        InformacoesAdicionais.setVisible(false);
        TituloTelaPerfil.setText("Bem vindo " + aux.getLogin());
        Status.setText("Status: "+aux.getStatus());
        if (aux.getNome() != null) {
            TextNomeTelaPerfil.setText("Nome: " + aux.getNome());

        }
        textUsuTelaPerfil.setText("Usuário: " + aux.getLogin());
        
        if (aux.getAltura() != 0 && aux.getPeso() != 0) {
            AlturaTelaPerfil.setText("Altura: " + aux.getAltura());
            PesoTelaPerfil.setText("Peso: " + aux.getPeso());
        } else {
            AlturaTelaPerfil.setText("");
            PesoTelaPerfil.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        AlterarNomeLogin = new javax.swing.JPanel();
        CorpooAlterarNome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        Nome1 = new javax.swing.JLabel();
        ConfirmSenha1 = new javax.swing.JLabel();
        ConfirmarAlteracaodoNome = new javax.swing.JButton();
        SairdaTelaAlterarUsu = new javax.swing.JButton();
        Confirmsenha = new javax.swing.JPasswordField();
        Objetivo = new javax.swing.JTextField();
        Cabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AlterarSenha = new javax.swing.JPanel();
        CabecalhoAlterarSenha = new javax.swing.JPanel();
        TituloAlterarSenha = new javax.swing.JLabel();
        IconeAlterarSenha = new javax.swing.JLabel();
        Icone2AlterarSenha = new javax.swing.JLabel();
        CorpoAlterarSenha = new javax.swing.JPanel();
        InformeCredeAlterarSenha = new javax.swing.JLabel();
        SenhaAtual1 = new javax.swing.JLabel();
        SenhaAtualAlterarSenha = new javax.swing.JTextField();
        NovaSenha1 = new javax.swing.JLabel();
        ConfirmSenha2 = new javax.swing.JLabel();
        botaoConfirmarAlterarSenha = new javax.swing.JButton();
        SairAlterarSenha = new javax.swing.JButton();
        NovaSenhaAlterarSenha = new javax.swing.JPasswordField();
        Confirmsenha1AlterarSenha = new javax.swing.JPasswordField();
        Perfil = new javax.swing.JPanel();
        OpcoesPerfil = new javax.swing.JPanel();
        DadosUsu = new javax.swing.JLabel();
        Altsenha = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        CorpoPerfil = new javax.swing.JPanel();
        TituloTelaPerfil = new javax.swing.JLabel();
        TextNomeTelaPerfil = new javax.swing.JLabel();
        textUsuTelaPerfil = new javax.swing.JLabel();
        AlturaTelaPerfil = new javax.swing.JLabel();
        PesoTelaPerfil = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        InformacoesAdicionais = new javax.swing.JPanel();
        cabecalhoInformacoes = new javax.swing.JPanel();
        TituloInformacoes = new javax.swing.JLabel();
        CorpoInformacoes = new javax.swing.JPanel();
        VariavelNomedeInformacoes = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JLabel();
        Nome3 = new javax.swing.JLabel();
        ConfirmSenhaInformacoes = new javax.swing.JLabel();
        Altpeso = new javax.swing.JTextField();
        AltAlt = new javax.swing.JTextField();
        Confirmsenha1Informacoes = new javax.swing.JPasswordField();
        ConfirmarInformacoes = new javax.swing.JButton();
        SairInformacoes = new javax.swing.JButton();

        
        setMinimumSize(new java.awt.Dimension(400, 410));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 410));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(588, 572));

        AlterarNomeLogin.setPreferredSize(new java.awt.Dimension(588, 572));

        CorpooAlterarNome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Informe suas credenciais");

        Usuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-administrador-masculino-24.png"))); // NOI18N
        Usuario1.setText("Alterar Objetivo:");

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        Nome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-conferência-24.png"))); // NOI18N
        Nome1.setText("Alterar Nome:");

        ConfirmSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        ConfirmSenha1.setText("Confirmar Senha:");

        ConfirmarAlteracaodoNome.setBackground(new java.awt.Color(58, 65, 84));
        ConfirmarAlteracaodoNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmarAlteracaodoNome.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarAlteracaodoNome.setText("Confirmar");
        ConfirmarAlteracaodoNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmarAlteracaodoNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmarAlteracaodoNomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfirmarAlteracaodoNomeMouseExited(evt);
            }
        });
        ConfirmarAlteracaodoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAlteracaodoNomeActionPerformed(evt);
            }
        });

        SairdaTelaAlterarUsu.setBackground(new java.awt.Color(217, 81, 51));
        SairdaTelaAlterarUsu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SairdaTelaAlterarUsu.setForeground(new java.awt.Color(255, 255, 255));
        SairdaTelaAlterarUsu.setText("Sair");
        SairdaTelaAlterarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SairdaTelaAlterarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairdaTelaAlterarUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairdaTelaAlterarUsuMouseExited(evt);
            }
        });
        SairdaTelaAlterarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairdaTelaAlterarUsuActionPerformed(evt);
            }
        });

        Confirmsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmsenhaActionPerformed(evt);
            }
        });

        Objetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoActionPerformed(evt);
            }
        });

        Cabecalho.setBackground(new java.awt.Color(27, 187, 125));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-usuário-do-usuário-de-segurança-100.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-usuário-de-segurança-feminino-100.png"))); // NOI18N

        javax.swing.GroupLayout CabecalhoLayout = new javax.swing.GroupLayout(Cabecalho);
        Cabecalho.setLayout(CabecalhoLayout);
        CabecalhoLayout.setHorizontalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabecalhoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addGap(43, 43, 43))
        );
        CabecalhoLayout.setVerticalGroup(
            CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabecalhoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabecalhoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout CorpooAlterarNomeLayout = new javax.swing.GroupLayout(CorpooAlterarNome);
        CorpooAlterarNome.setLayout(CorpooAlterarNomeLayout);
        CorpooAlterarNomeLayout.setHorizontalGroup(
            CorpooAlterarNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpooAlterarNomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(CorpooAlterarNomeLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(CorpooAlterarNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SairdaTelaAlterarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome1)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario1)
                    .addComponent(Objetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmSenha1)
                    .addComponent(Confirmsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmarAlteracaodoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CorpooAlterarNomeLayout.setVerticalGroup(
            CorpooAlterarNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpooAlterarNomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(Nome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Objetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirmsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ConfirmarAlteracaodoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SairdaTelaAlterarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AlterarNomeLoginLayout = new javax.swing.GroupLayout(AlterarNomeLogin);
        AlterarNomeLogin.setLayout(AlterarNomeLoginLayout);
        AlterarNomeLoginLayout.setHorizontalGroup(
            AlterarNomeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CorpooAlterarNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AlterarNomeLoginLayout.setVerticalGroup(
            AlterarNomeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarNomeLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CorpooAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AlterarSenha.setPreferredSize(new java.awt.Dimension(588, 572));

        CabecalhoAlterarSenha.setBackground(new java.awt.Color(27, 187, 125));

        TituloAlterarSenha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TituloAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        TituloAlterarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloAlterarSenha.setText("Alterar Senha");

        IconeAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-cadeado-2-100.png"))); // NOI18N

        Icone2AlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-bloqueio-de-segurança-amarelo-100 (1).png"))); // NOI18N

        CorpoAlterarSenha.setBackground(new java.awt.Color(255, 255, 255));
        CorpoAlterarSenha.setPreferredSize(new java.awt.Dimension(480, 477));

        InformeCredeAlterarSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InformeCredeAlterarSenha.setText("Informe suas credenciais");

        SenhaAtual1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SenhaAtual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        SenhaAtual1.setText("Senha Atual:");

        SenhaAtualAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaAtualAlterarSenhaActionPerformed(evt);
            }
        });

        NovaSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NovaSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        NovaSenha1.setText("Nova senha:");

        ConfirmSenha2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmSenha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        ConfirmSenha2.setText("Confirmar Senha:");

        botaoConfirmarAlterarSenha.setBackground(new java.awt.Color(58, 65, 84));
        botaoConfirmarAlterarSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoConfirmarAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        botaoConfirmarAlterarSenha.setText("Confirmar");
        botaoConfirmarAlterarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoConfirmarAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoConfirmarAlterarSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoConfirmarAlterarSenhaMouseExited(evt);
            }
        });
        botaoConfirmarAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarAlterarSenhaActionPerformed(evt);
            }
        });

        SairAlterarSenha.setBackground(new java.awt.Color(217, 81, 51));
        SairAlterarSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SairAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        SairAlterarSenha.setText("Sair");
        SairAlterarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SairAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairAlterarSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairAlterarSenhaMouseExited(evt);
            }
        });
        SairAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairAlterarSenhaActionPerformed(evt);
            }
        });

        Confirmsenha1AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmsenha1AlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CorpoAlterarSenhaLayout = new javax.swing.GroupLayout(CorpoAlterarSenha);
        CorpoAlterarSenha.setLayout(CorpoAlterarSenhaLayout);
        CorpoAlterarSenhaLayout.setHorizontalGroup(
            CorpoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpoAlterarSenhaLayout.createSequentialGroup()
                .addGroup(CorpoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CorpoAlterarSenhaLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(InformeCredeAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CorpoAlterarSenhaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(CorpoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhaAtualAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SenhaAtual1)
                            .addComponent(NovaSenha1)
                            .addComponent(NovaSenhaAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmSenha2)
                            .addComponent(Confirmsenha1AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoConfirmarAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SairAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CorpoAlterarSenhaLayout.setVerticalGroup(
            CorpoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpoAlterarSenhaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(InformeCredeAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhaAtual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaAtualAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NovaSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NovaSenhaAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirmsenha1AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botaoConfirmarAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SairAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CabecalhoAlterarSenhaLayout = new javax.swing.GroupLayout(CabecalhoAlterarSenha);
        CabecalhoAlterarSenha.setLayout(CabecalhoAlterarSenhaLayout);
        CabecalhoAlterarSenhaLayout.setHorizontalGroup(
            CabecalhoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabecalhoAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconeAlterarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(TituloAlterarSenha)
                .addGap(30, 30, 30)
                .addComponent(Icone2AlterarSenha)
                .addGap(34, 34, 34))
            .addComponent(CorpoAlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        CabecalhoAlterarSenhaLayout.setVerticalGroup(
            CabecalhoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabecalhoAlterarSenhaLayout.createSequentialGroup()
                .addGroup(CabecalhoAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconeAlterarSenha)
                    .addComponent(Icone2AlterarSenha)
                    .addGroup(CabecalhoAlterarSenhaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TituloAlterarSenha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CorpoAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AlterarSenhaLayout = new javax.swing.GroupLayout(AlterarSenha);
        AlterarSenha.setLayout(AlterarSenhaLayout);
        AlterarSenhaLayout.setHorizontalGroup(
            AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CabecalhoAlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AlterarSenhaLayout.setVerticalGroup(
            AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlterarSenhaLayout.createSequentialGroup()
                .addComponent(CabecalhoAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Perfil.setPreferredSize(new java.awt.Dimension(588, 572));

        OpcoesPerfil.setBackground(new java.awt.Color(242, 242, 242));

        DadosUsu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DadosUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-administrador-masculino-24.png"))); // NOI18N
        DadosUsu.setText("Alterar dados de usuário");
        DadosUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DadosUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DadosUsuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DadosUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DadosUsuMouseExited(evt);
            }
        });
        DadosUsu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DadosUsuComponentShown(evt);
            }
        });

        Altsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Altsenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        Altsenha.setText("Alterar Senha");
        Altsenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Altsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AltsenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AltsenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AltsenhaMouseExited(evt);
            }
        });

        Info.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addition-sign.png"))); // NOI18N
        Info.setText("Informacoes adicionais");
        Info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoMouseExited(evt);
            }
        });

        Inicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pessoa-em-casa-24.png"))); // NOI18N
        Inicio.setText("Inicio");
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEKmZWL.png"))); // NOI18N
        Logo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoMouseMoved(evt);
            }
        });
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoMouseExited(evt);
            }
        });

        CorpoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        CorpoPerfil.setPreferredSize(new java.awt.Dimension(344, 406));

        TituloTelaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloTelaPerfil.setText("Bem vindo Vinicius");
        TituloTelaPerfil.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TituloTelaPerfilInputMethodTextChanged(evt);
            }
        });

        TextNomeTelaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextNomeTelaPerfil.setText("Nome:");

        textUsuTelaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textUsuTelaPerfil.setText("Usuário:");

        AlturaTelaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlturaTelaPerfil.setText("Altura:");

        PesoTelaPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PesoTelaPerfil.setText("Peso:");

        Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Status.setText("Status:");

        javax.swing.GroupLayout CorpoPerfilLayout = new javax.swing.GroupLayout(CorpoPerfil);
        CorpoPerfil.setLayout(CorpoPerfilLayout);
        CorpoPerfilLayout.setHorizontalGroup(
            CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpoPerfilLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNomeTelaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlturaTelaPerfil)
                    .addGroup(CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpoPerfilLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(TituloTelaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addComponent(Status))
                            .addGroup(CorpoPerfilLayout.createSequentialGroup()
                                .addComponent(PesoTelaPerfil)
                                .addGap(18, 18, 18)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpoPerfilLayout.createSequentialGroup()
                            .addComponent(textUsuTelaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)))))
        );
        CorpoPerfilLayout.setVerticalGroup(
            CorpoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpoPerfilLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(TituloTelaPerfil)
                .addGap(79, 79, 79)
                .addComponent(Status)
                .addGap(72, 72, 72)
                .addComponent(TextNomeTelaPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(textUsuTelaPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AlturaTelaPerfil)
                .addGap(75, 75, 75)
                .addComponent(PesoTelaPerfil)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout OpcoesPerfilLayout = new javax.swing.GroupLayout(OpcoesPerfil);
        OpcoesPerfil.setLayout(OpcoesPerfilLayout);
        OpcoesPerfilLayout.setHorizontalGroup(
            OpcoesPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesPerfilLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(OpcoesPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DadosUsu)
                    .addComponent(Info)
                    .addComponent(Altsenha)
                    .addGroup(OpcoesPerfilLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Logo))
                    .addGroup(OpcoesPerfilLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Inicio)))
                .addGap(77, 77, 77)
                .addComponent(CorpoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        OpcoesPerfilLayout.setVerticalGroup(
            OpcoesPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcoesPerfilLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Logo)
                .addGap(55, 55, 55)
                .addComponent(Inicio)
                .addGap(72, 72, 72)
                .addComponent(DadosUsu)
                .addGap(78, 78, 78)
                .addComponent(Altsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(Info)
                .addContainerGap(104, Short.MAX_VALUE))
            .addComponent(CorpoPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PerfilLayout = new javax.swing.GroupLayout(Perfil);
        Perfil.setLayout(PerfilLayout);
        PerfilLayout.setHorizontalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilLayout.createSequentialGroup()
                .addComponent(OpcoesPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PerfilLayout.setVerticalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcoesPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InformacoesAdicionais.setPreferredSize(new java.awt.Dimension(588, 572));

        cabecalhoInformacoes.setBackground(new java.awt.Color(27, 187, 125));

        TituloInformacoes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TituloInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        TituloInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloInformacoes.setText("Informações");

        javax.swing.GroupLayout cabecalhoInformacoesLayout = new javax.swing.GroupLayout(cabecalhoInformacoes);
        cabecalhoInformacoes.setLayout(cabecalhoInformacoesLayout);
        cabecalhoInformacoesLayout.setHorizontalGroup(
            cabecalhoInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoInformacoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloInformacoes)
                .addGap(172, 172, 172))
        );
        cabecalhoInformacoesLayout.setVerticalGroup(
            cabecalhoInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoInformacoesLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(TituloInformacoes)
                .addGap(31, 31, 31))
        );

        CorpoInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        CorpoInformacoes.setPreferredSize(new java.awt.Dimension(588, 439));

        VariavelNomedeInformacoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VariavelNomedeInformacoes.setText("Nome :");

        Usuario2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-escala-20.png"))); // NOI18N
        Usuario2.setText("Alterar Peso :");

        Nome3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-altura-24.png"))); // NOI18N
        Nome3.setText("Alterar Altura :");

        ConfirmSenhaInformacoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmSenhaInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-senha-24.png"))); // NOI18N
        ConfirmSenhaInformacoes.setText("Confirmar Senha :");

        Altpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltpesoActionPerformed(evt);
            }
        });

        AltAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltAltActionPerformed(evt);
            }
        });

        Confirmsenha1Informacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmsenha1InformacoesActionPerformed(evt);
            }
        });

        ConfirmarInformacoes.setBackground(new java.awt.Color(58, 65, 84));
        ConfirmarInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmarInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarInformacoes.setText("Confirmar");
        ConfirmarInformacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmarInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmarInformacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfirmarInformacoesMouseExited(evt);
            }
        });
        ConfirmarInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarInformacoesActionPerformed(evt);
            }
        });

        SairInformacoes.setBackground(new java.awt.Color(217, 81, 51));
        SairInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SairInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        SairInformacoes.setText("Sair");
        SairInformacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SairInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairInformacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairInformacoesMouseExited(evt);
            }
        });
        SairInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairInformacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CorpoInformacoesLayout = new javax.swing.GroupLayout(CorpoInformacoes);
        CorpoInformacoes.setLayout(CorpoInformacoesLayout);
        CorpoInformacoesLayout.setHorizontalGroup(
            CorpoInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpoInformacoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VariavelNomedeInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(CorpoInformacoesLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(CorpoInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SairInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmarInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmsenha1Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Altpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AltAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmSenhaInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario2)
                    .addComponent(Nome3))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        CorpoInformacoesLayout.setVerticalGroup(
            CorpoInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpoInformacoesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(VariavelNomedeInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Nome3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AltAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Altpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmSenhaInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Confirmsenha1Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmarInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SairInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InformacoesAdicionaisLayout = new javax.swing.GroupLayout(InformacoesAdicionais);
        InformacoesAdicionais.setLayout(InformacoesAdicionaisLayout);
        InformacoesAdicionaisLayout.setHorizontalGroup(
            InformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CorpoInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cabecalhoInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InformacoesAdicionaisLayout.setVerticalGroup(
            InformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacoesAdicionaisLayout.createSequentialGroup()
                .addComponent(cabecalhoInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CorpoInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(AlterarNomeLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AlterarSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Perfil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(InformacoesAdicionais, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AlterarNomeLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InformacoesAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AlterarNomeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InformacoesAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarAlteracaodoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAlteracaodoNomeActionPerformed
        
        if (Confirmsenha.getText().equals(aux.getSenha())) {
            aux.setObjetivo(Objetivo.getText());
            aux.setNome(Nome.getText());
            dao.AtualizarLogineObjetivo(aux);
            AlterarNomeLogin.setVisible(false);

            TituloTelaPerfil.setText("Bem vindo " + aux.getLogin());
            if (aux.getNome() != null) {
                TextNomeTelaPerfil.setText("Nome: " + aux.getNome());

            }
            textUsuTelaPerfil.setText("Usuário: " + aux.getLogin());
            if (aux.getAltura() != 0 && aux.getPeso() != 0) {
                AlturaTelaPerfil.setText("Altura: " + aux.getAltura());
                PesoTelaPerfil.setText("Peso: " + aux.getPeso());
            } else {
                AlturaTelaPerfil.setText("");
                PesoTelaPerfil.setText("");
            }
            Perfil.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta");
        }


    }//GEN-LAST:event_ConfirmarAlteracaodoNomeActionPerformed

    private void ConfirmsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmsenhaActionPerformed

    private void ConfirmarAlteracaodoNomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarAlteracaodoNomeMouseEntered
        ConfirmarAlteracaodoNome.setBackground(new Color(235, 235, 235));
        ConfirmarAlteracaodoNome.setForeground(new Color(58, 65, 84));
    }//GEN-LAST:event_ConfirmarAlteracaodoNomeMouseEntered

    private void SairdaTelaAlterarUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairdaTelaAlterarUsuMouseEntered

        SairdaTelaAlterarUsu.setBackground(new Color(235, 235, 235));
        SairdaTelaAlterarUsu.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_SairdaTelaAlterarUsuMouseEntered

    private void ConfirmarAlteracaodoNomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarAlteracaodoNomeMouseExited
        ConfirmarAlteracaodoNome.setBackground(new Color(58, 65, 84));
        ConfirmarAlteracaodoNome.setForeground(Color.WHITE);
    }//GEN-LAST:event_ConfirmarAlteracaodoNomeMouseExited

    private void SairdaTelaAlterarUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairdaTelaAlterarUsuMouseExited
        SairdaTelaAlterarUsu.setBackground(new Color(217, 81, 51));
        SairdaTelaAlterarUsu.setForeground(Color.WHITE);
    }//GEN-LAST:event_SairdaTelaAlterarUsuMouseExited

    private void SairdaTelaAlterarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairdaTelaAlterarUsuActionPerformed
        AlterarNomeLogin.setVisible(false);
        Perfil.setVisible(true);

    }//GEN-LAST:event_SairdaTelaAlterarUsuActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void DadosUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DadosUsuMouseClicked
        // TODO add your handling code here:
        Perfil.setVisible(false);
        AlterarNomeLogin.setVisible(true);
    }//GEN-LAST:event_DadosUsuMouseClicked

    private void DadosUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DadosUsuMouseEntered
        DadosUsu.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_DadosUsuMouseEntered

    private void DadosUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DadosUsuMouseExited
        DadosUsu.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_DadosUsuMouseExited

    private void DadosUsuComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DadosUsuComponentShown

    }//GEN-LAST:event_DadosUsuComponentShown

    private void AltsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltsenhaMouseClicked
        // TODO add your handling code here:
        Perfil.setVisible(false);
        AlterarSenha.setVisible(true);
    }//GEN-LAST:event_AltsenhaMouseClicked

    private void AltsenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltsenhaMouseEntered
        Altsenha.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_AltsenhaMouseEntered

    private void AltsenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltsenhaMouseExited
        Altsenha.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_AltsenhaMouseExited

    private void InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseClicked
        // TODO add your handling code here:
        VariavelNomedeInformacoes.setText(aux.getNome());
        InformacoesAdicionais.setVisible(true);
        Perfil.setVisible(false);

    }//GEN-LAST:event_InfoMouseClicked

    private void InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseEntered
        Info.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_InfoMouseEntered

    private void InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMouseExited
        Info.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_InfoMouseExited

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // TODO add your handling code here:
        setVisible(false);

//        Inicial I = new Inicial(aux);
//        I.setVisible(true);

    }//GEN-LAST:event_InicioMouseClicked

    private void InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseEntered
        Inicio.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_InicioMouseEntered

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited
        // TODO add your handling code here:
        Inicio.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_InicioMouseExited

    private void LogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseMoved
        //        jLabel1.setText("www");
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pXzLOUi.png"))); // NOI18N);
    }//GEN-LAST:event_LogoMouseMoved

    private void LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseExited
        //        jLabel1.setText("");
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MEKmZWl.png"))); // NOI18N);
    }//GEN-LAST:event_LogoMouseExited

    private void TituloTelaPerfilInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TituloTelaPerfilInputMethodTextChanged
        //        Titulo.setText("Bem vindo");
    }//GEN-LAST:event_TituloTelaPerfilInputMethodTextChanged

    private void SenhaAtualAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaAtualAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaAtualAlterarSenhaActionPerformed

    private void botaoConfirmarAlterarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarAlterarSenhaMouseEntered
        botaoConfirmarAlterarSenha.setBackground(new Color(235, 235, 235));
        botaoConfirmarAlterarSenha.setForeground(new Color(58, 65, 84));
    }//GEN-LAST:event_botaoConfirmarAlterarSenhaMouseEntered

    private void botaoConfirmarAlterarSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConfirmarAlterarSenhaMouseExited
        botaoConfirmarAlterarSenha.setBackground(new Color(58, 65, 84));
        botaoConfirmarAlterarSenha.setForeground(Color.WHITE);
    }//GEN-LAST:event_botaoConfirmarAlterarSenhaMouseExited

    private void botaoConfirmarAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarAlterarSenhaActionPerformed

        if (SenhaAtualAlterarSenha.getText().equals(aux.getSenha())) {
            if (NovaSenhaAlterarSenha.getText().equals(Confirmsenha1AlterarSenha.getText())) {
                aux.setSenha(NovaSenhaAlterarSenha.getText());
                dao.AtualizarSenha(aux);
                AlterarSenha.setVisible(false);
                Perfil.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Senhas Alteradas nao correspondem");


    }//GEN-LAST:event_botaoConfirmarAlterarSenhaActionPerformed
        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta");
        }
    }
    private void SairAlterarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairAlterarSenhaMouseEntered

        SairAlterarSenha.setBackground(new Color(235, 235, 235));
        SairAlterarSenha.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_SairAlterarSenhaMouseEntered

    private void SairAlterarSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairAlterarSenhaMouseExited
        SairAlterarSenha.setBackground(new Color(217, 81, 51));
        SairAlterarSenha.setForeground(Color.WHITE);
    }//GEN-LAST:event_SairAlterarSenhaMouseExited

    private void SairAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairAlterarSenhaActionPerformed
        AlterarSenha.setVisible(false);
        Perfil.setVisible(true);
    }//GEN-LAST:event_SairAlterarSenhaActionPerformed

    private void Confirmsenha1AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmsenha1AlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirmsenha1AlterarSenhaActionPerformed

    private void AltpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AltpesoActionPerformed

    private void AltAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AltAltActionPerformed

    private void Confirmsenha1InformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmsenha1InformacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirmsenha1InformacoesActionPerformed

    private void ConfirmarInformacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarInformacoesMouseEntered
        ConfirmarInformacoes.setBackground(new Color(235, 235, 235));
        ConfirmarInformacoes.setForeground(new Color(58, 65, 84));
    }//GEN-LAST:event_ConfirmarInformacoesMouseEntered

    private void ConfirmarInformacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarInformacoesMouseExited
        ConfirmarInformacoes.setBackground(new Color(58, 65, 84));
        ConfirmarInformacoes.setForeground(Color.WHITE);
    }//GEN-LAST:event_ConfirmarInformacoesMouseExited

    private void ConfirmarInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarInformacoesActionPerformed

        if (Confirmsenha1Informacoes.getText().equals(aux.getSenha())) {
            aux.setAltura(Double.parseDouble(AltAlt.getText()));
            aux.setPeso(Double.parseDouble(Altpeso.getText()));
            dao.AtualizarInformacoes(aux);
            AlturaTelaPerfil.setText("Altura: " + aux.getAltura());
            PesoTelaPerfil.setText("Peso: " + aux.getPeso());
            InformacoesAdicionais.setVisible(false);
            Perfil.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta");
        }

    }//GEN-LAST:event_ConfirmarInformacoesActionPerformed

    private void SairInformacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairInformacoesMouseEntered

        SairInformacoes.setBackground(new Color(235, 235, 235));
        SairInformacoes.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_SairInformacoesMouseEntered

    private void SairInformacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairInformacoesMouseExited
        SairInformacoes.setBackground(new Color(217, 81, 51));
        SairInformacoes.setForeground(Color.WHITE);
    }//GEN-LAST:event_SairInformacoesMouseExited

    private void SairInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairInformacoesActionPerformed
        InformacoesAdicionais.setVisible(false);
        Perfil.setVisible(true);

    }//GEN-LAST:event_SairInformacoesActionPerformed

    private void ObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObjetivoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AlterarSenha().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AltAlt;
    private javax.swing.JPanel AlterarNomeLogin;
    private javax.swing.JPanel AlterarSenha;
    private javax.swing.JTextField Altpeso;
    private javax.swing.JLabel Altsenha;
    private javax.swing.JLabel AlturaTelaPerfil;
    private javax.swing.JPanel Cabecalho;
    private javax.swing.JPanel CabecalhoAlterarSenha;
    private javax.swing.JLabel ConfirmSenha1;
    private javax.swing.JLabel ConfirmSenha2;
    private javax.swing.JLabel ConfirmSenhaInformacoes;
    private javax.swing.JButton ConfirmarAlteracaodoNome;
    private javax.swing.JButton ConfirmarInformacoes;
    private javax.swing.JPasswordField Confirmsenha;
    private javax.swing.JPasswordField Confirmsenha1AlterarSenha;
    private javax.swing.JPasswordField Confirmsenha1Informacoes;
    private javax.swing.JPanel CorpoAlterarSenha;
    private javax.swing.JPanel CorpoInformacoes;
    private javax.swing.JPanel CorpoPerfil;
    private javax.swing.JPanel CorpooAlterarNome;
    private javax.swing.JLabel DadosUsu;
    private javax.swing.JLabel Icone2AlterarSenha;
    private javax.swing.JLabel IconeAlterarSenha;
    private javax.swing.JLabel Info;
    private javax.swing.JPanel InformacoesAdicionais;
    private javax.swing.JLabel InformeCredeAlterarSenha;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel Nome3;
    private javax.swing.JLabel NovaSenha1;
    private javax.swing.JPasswordField NovaSenhaAlterarSenha;
    private javax.swing.JTextField Objetivo;
    private javax.swing.JPanel OpcoesPerfil;
    private javax.swing.JPanel Perfil;
    private javax.swing.JLabel PesoTelaPerfil;
    private javax.swing.JButton SairAlterarSenha;
    private javax.swing.JButton SairInformacoes;
    private javax.swing.JButton SairdaTelaAlterarUsu;
    private javax.swing.JLabel SenhaAtual1;
    private javax.swing.JTextField SenhaAtualAlterarSenha;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel TextNomeTelaPerfil;
    private javax.swing.JLabel TituloAlterarSenha;
    private javax.swing.JLabel TituloInformacoes;
    private javax.swing.JLabel TituloTelaPerfil;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel VariavelNomedeInformacoes;
    private javax.swing.JButton botaoConfirmarAlterarSenha;
    private javax.swing.JPanel cabecalhoInformacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel textUsuTelaPerfil;
    // End of variables declaration//GEN-END:variables
}
